import 'package:flutter/material.dart';

const Color primaryColor = Color(0xFF1d70be);
const Color primaryColorLight = Color(0xFF66acee);
const Color primaryColorDark = Color(0xFF1b4975);
const Color secondaryColor = Color(0xFFe22635);
const Color secondaryColorLight = Color(0xFFee818a);
const Color tertiaryColor = Color(0xFF51db4a);
const Color textColorWhite = Color(0xFFffffff);
const Color textColorBlack = Color(0xFF000000);
const Color textColorGrey = Color(0xFF545454);
const Color textColorLightGrey = Color(0xFFb6b6b6);
const Color textColorRed = Color(0xFFfe1c1c);
const Color textColorGreen = Color(0xFF0dcb00);
const Color textColorDarkBlue = Color(0xFF003049);
const Color textColorLightBlue = Color(0xFF376c87);
const Color shadowColor = Color(0xFF535353);
const Color widgetGreyColor = Color(0xFF545454);
const Color widgetLightGreyColor = Color(0xFFb6b6b6);
const Color lightShadowColor = Color(0xFFE0E0E0);
const Color widgetBgColor = Color(0xFFffffff);
const Color transparent = Color(0x00000000);
const Color textColorRedDark = Color(0xFFC70039 );